language: java
jdk: oraclejdk8
branches:
  except:
    - /^build@.*/
install:
  - mvn clean install
cache:
  directories:
    - .autoconf
    - $HOME/.m2
notifications:
  email: false
  webhooks:
    urls:
      secure: "nCqPt9CxCWMB/zMDhPuB/W49vtL/6jJ29B5wSL6dQG7vQEapZ2ONW42+mtD5+GkGXjgQABeto+ADlrFG0tAdOkYLvBlYl/8wRrp0ZS5PIvpX88BFw3329TukOIQkU0WTQ2D2BK055wLRJaEAt9BGKs/ER+I+KxLUDc7dt5IjGWh1R6Kl4fcFbaUME5MpVShL+4TPIysBrOJ7sYs1Lomfs+CaUUrVkkvKIbRJEnTTPWIoMHKwU/gsheKu2UoaoZb/msQXFlAEqQZZlHneHd6wEdEOxFBxVem8qnSh5+a5eRk3o1nHKtz4/LTRiNau4IW+3tUXW7ao4mxCjuaMbTtiBVWs01YI87z0QvZwwK7hCN/9JxugAfwnxRhZuWfxcIBKbrtE8UZPXokE3ESVYYv1jcZbB0iwaM5vf+jsiRW2GfQJ7L0VvSfGpRGIn7yHJiZK0ZNyOrxnNM2j2IjwKBCar7F//nlB/0h3Puavtn2NZaVGMKURoQyJoa94LZHKSsX/6sblOdAXV/LkEORhCkzQNxK33GnkfrJ9KFBDCDsV6y1XvE4+mZbElGofDNQUHeeVcDdE213OrAWYRkM1LNHbLE4bVeH9vvrpoHcXDxBp0pFYB5pgC8BhcGn2hdNzyJrUMi3uZsQ9Vbf9aMb3cRgYF5rJLV8zJDOkVOJZ7PtDkdo="
before_deploy:
  - mvn package
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build@${TRAVIS_BRANCH}#${TRAVIS_BUILD_NUMBER}
  - git tag ${GIT_TAG} -a -m "Generated tag from TravisCI build ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet https://${GITHUB_TOKEN}@github.com/Team-Fruit/FactorioForge ${GIT_TAG} > /dev/null 2>&1
deploy:
  provider: releases
  prerelease: true
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: '! "$TRAVIS_BRANCH" =~ ^(dev\\-|feature\\/).*$'